version: "3.8"

services:
  backend:
    build:
      context: ./alpr-backend  # Path to your backend repo
      dockerfile: Dockerfile  # Path to your backend Dockerfile
    container_name: alpr-backend
    ports:
      - "8000:8000"
    volumes:
      - ./alpr-backend:/app  # Mount the backend code
    environment:
      - DB_URL=postgresql://user:password@db:5432/alpr  # Update as per your DB settings
      - AUTO_OCR_ENABLED=True  # Example environment variable for backend
    depends_on:
      - db

  frontend:
    build:
      context: ./smart-alpr-frontend  # Path to your frontend repo
      dockerfile: Dockerfile  # Path to your frontend Dockerfile (if needed)
    container_name: alpr-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./smart-alpr-frontend:/app  # Mount the frontend code
    environment:
      - VITE_API_URL=http://backend:8000  # Example env var for frontend to call backend

  db:
    image: postgres:latest
    container_name: alpr-db
    environment:
      POSTGRES_DB: alpr
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - alpr-db-data:/var/lib/postgresql/data  # Persist database data

volumes:
  alpr-db-data:
